/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_mi_mp3_util_LameUtil */

#ifndef _Included_me_mi_mp3_util_LameUtil
#define _Included_me_mi_mp3_util_LameUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_mi_mp3_util_LameUtil
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_me_mi_mp3_util_LameUtil_init
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     me_mi_mp3_util_LameUtil
 * Method:    encode
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_me_mi_mp3_util_LameUtil_encode
  (JNIEnv *, jclass, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     me_mi_mp3_util_LameUtil
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_me_mi_mp3_util_LameUtil_flush
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     me_mi_mp3_util_LameUtil
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_mi_mp3_util_LameUtil_close
  (JNIEnv *, jclass);

/*
 * Class:     me_mi_mp3_util_LameUtil
 * Method:    encodeFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_me_mi_mp3_util_LameUtil_encodeFile
  (JNIEnv *, jobject, jstring, jstring);
  
#ifdef __cplusplus
}
#endif
#endif
